# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: true

pull_requests: true

statuses:
  differences: true
  no_differences: true
  error: true

restylers:
  - name: clang-format
    include:
      - "**/*.h"
      - "**/*.cpp"
      - "!/glslang/*"

  - name: astyle
    include:
      - "**/*.h"
      - "**/*.cpp"
      - "!/glslang/*"
