sudo: false

language: cpp

addons:
  apt:
    packages:
      - cmake
      - libprotobuf-dev
      - protobuf-compiler

  homebrew:
    packages:
      - protobuf

  chocolatey:
    packages:
      - protoc

matrix:
  include:
    - name: "webassembly"
      os: linux
      dist: bionic
      env:
        - NAME=webassembly
        - BEFORE_BUILD="git clone https://github.com/emscripten-core/emsdk.git && pushd emsdk && ./emsdk install latest && ./emsdk activate latest && popd"
        - BUILD="source emsdk/emsdk_env.sh && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake .. && make -j2"

before_install:
  - eval "${BEFORE_BUILD}"

script:
  - eval "${BUILD}"
