name: CI

on: [push]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build

  linux-gcc-gpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.1.92.1"
        key: vulkansdk-linux-x86_64-1.1.92.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz && tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz
    - name: configure
      run: export VULKAN_SDK=`pwd`/1.1.92.1/x86_64 && mkdir build && cd build && cmake -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler
    - name: configure
      env:
        CC: clang
        CXX: clang++
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build

  linux-clang-gpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.1.92.1"
        key: vulkansdk-linux-x86_64-1.1.92.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz && tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz
    - name: configure
      env:
        CC: clang
        CXX: clang++
      run: export VULKAN_SDK=`pwd`/1.1.92.1/x86_64 && mkdir build && cd build && cmake -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: brew install protobuf
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build

  macos-clang-gpu:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: brew install protobuf
    - name: vulkansdk
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz?Human=true -O vulkansdk-macos-1.1.92.1.tar.gz && tar -xf vulkansdk-macos-1.1.92.1.tar.gz
    - name: configure
      run: export VULKAN_SDK=`pwd`/vulkansdk-macos-1.1.92.1/macOS && mkdir build && cd build && cmake -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  windows-vs2019:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: choco install protoc
    - name: configure
      run: mkdir build; cd build; cmake ..
    - name: build
      run: cmake --build build

  windows-vs2019-gpu:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: protobuf
      run: choco install protoc
    - name: vulkansdk
      run: Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.1.92.1/windows/VulkanSDK-1.1.92.1-Installer.exe?Human=true -OutFile VulkanSDK-1.1.92.1-Installer.exe; 7z x ./VulkanSDK-1.1.92.1-Installer.exe -oVulkanSDK
    - name: configure
      run: $env:VULKAN_SDK="$(pwd)/VulkanSDK"; mkdir build; cd build; cmake -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  android-armv7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-14 ..
    - name: build
      run: cmake --build build

  android-armv7-gpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.1.92.1"
        key: vulkansdk-linux-x86_64-1.1.92.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz && tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz
    - name: configure
      run: export PATH=`pwd`/1.1.92.1/x86_64/bin:$PATH && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  android-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-21 ..
    - name: build
      run: cmake --build build

  android-aarch64-gpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.1.92.1"
        key: vulkansdk-linux-x86_64-1.1.92.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz && tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz
    - name: configure
      run: export PATH=`pwd`/1.1.92.1/x86_64/bin:$PATH && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  android-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="x86"  -DANDROID_PLATFORM=android-14 ..
    - name: build
      run: cmake --build build

  android-x86-gpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.1.92.1"
        key: vulkansdk-linux-x86_64-1.1.92.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz && tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz
    - name: configure
      run: export PATH=`pwd`/1.1.92.1/x86_64/bin:$PATH && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="x86" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  android-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="x86_64" -DANDROID_PLATFORM=android-21 ..
    - name: build
      run: cmake --build build

  android-x86_64-gpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cache-androidndk
      id: cache-androidndk
      uses: actions/cache@v1
      with:
        path: "android-ndk-r19c"
        key: android-ndk-r19c-linux-x86_64
    - name: androidndk
      if: steps.cache-androidndk.outputs.cache-hit != 'true'
      run: wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip && unzip -q android-ndk-r19c-linux-x86_64.zip
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.1.92.1"
        key: vulkansdk-linux-x86_64-1.1.92.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz && tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz
    - name: configure
      run: export PATH=`pwd`/1.1.92.1/x86_64/bin:$PATH && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../android-ndk-r19c/build/cmake/android.toolchain.cmake -DANDROID_ABI="x86_64" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  ios-iphoneos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=OS ..
    - name: build
      run: cmake --build build

  ios-iphoneos-gpu:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: vulkansdk
      run: wget https://sdk.lunarg.com/sdk/download/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz?Human=true -O vulkansdk-macos-1.1.92.1.tar.gz && tar -xf vulkansdk-macos-1.1.92.1.tar.gz
    - name: configure
      run: export VULKAN_SDK=`pwd`/vulkansdk-macos-1.1.92.1/macOS && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=OS64 -DVulkan_INCLUDE_DIR=`pwd`/../vulkansdk-macos-1.1.92.1/MoltenVK/include -DVulkan_LIBRARY=`pwd`/../vulkansdk-macos-1.1.92.1/MoltenVK/iOS/dynamic/libMoltenVK.dylib -DNCNN_VULKAN=ON ..
    - name: build
      run: cmake --build build

  ios-iphonesimulator:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR ..
    - name: build
      run: cmake --build build
