name: windows-x64-gpu-vs2019
on: [push, pull_request]
jobs:
  windows-vs2019-gpu:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: cache-protobuf
      id: cache-protobuf
      uses: actions/cache@v1
      with:
        path: "protobuf-install"
        key: protobuf-windows-install
    - name: protobuf
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/archive/v3.11.2.zip -OutFile protobuf-3.11.2.zip
        7z x ./protobuf-3.11.2.zip
        cd protobuf-3.11.2
        mkdir build-vs2019; cd build-vs2019; cmake -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE\protobuf-install" -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -DNCNN_BUILD_TESTS=ON ../cmake
        cmake --build . --config Release -j 2
        cmake --build . --config Release --target install
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "VulkanSDK"
        key: VulkanSDK-1.2.148.1-Installer
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.148.1/windows/VulkanSDK-1.2.148.1-Installer.exe?Human=true -OutFile VulkanSDK-1.2.148.1-Installer.exe
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.148.1/windows/vulkan-runtime-components.zip?Human=true -OutFile vulkan-runtime-components.zip

        7z x -aoa ./VulkanSDK-1.2.148.1-Installer.exe -oVulkanSDK
        7z x -aoa ./vulkan-runtime-components.zip -ovulkan-runtime-components

        Remove-Item .\VulkanSDK\Bin, .\VulkanSDK\Bin32, .\VulkanSDK\Demos, .\VulkanSDK\Samples, .\VulkanSDK\Templates, .\VulkanSDK\Third-Party, .\VulkanSDK\Tools, .\VulkanSDK\Tools32 -Recurse

        Move-Item .\VulkanSDK\Include\vulkan .\VulkanSDK\vulkan
        Remove-Item .\VulkanSDK\Include\* -Recurse
        Move-Item .\VulkanSDK\vulkan .\VulkanSDK\Include\vulkan

        Move-Item .\VulkanSDK\Lib\vulkan-1.lib .\VulkanSDK\vulkan-1.lib
        Remove-Item .\VulkanSDK\Lib\* -Recurse
        Move-Item .\VulkanSDK\vulkan-1.lib .\VulkanSDK\Lib\vulkan-1.lib

        Remove-Item .\VulkanSDK\Lib32\* -Recurse

        Move-Item .\vulkan-runtime-components\VulkanRT-1.2.148.1-Components\x64\vulkan-1.dll .\VulkanSDK\vulkan-1.dll
    - name: cache-swiftshader
      id: cache-swiftshader
      uses: actions/cache@v1
      with:
        path: swiftshader-install
        key: swiftshader-windows-install-20201103
    - name: checkout-swiftshader
      if: steps.cache-swiftshader.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: google/swiftshader
        path: swiftshader
        ref: 959f41988a18e8511dcde1d646d798de4ea6b59d
    - name: checkout-swiftshader-submodules
      if: steps.cache-swiftshader.outputs.cache-hit != 'true'
      run: |
        cd swiftshader
        git submodule update --init --recursive
    - name: swiftshader
      if: steps.cache-swiftshader.outputs.cache-hit != 'true'
      run: |
        cd swiftshader
        mkdir build-vs2019; cd build-vs2019
        cmake -DCMAKE_INSTALL_PREFIX=install -DSWIFTSHADER_BUILD_EGL=FALSE -DSWIFTSHADER_BUILD_GLESv2=FALSE -DSWIFTSHADER_BUILD_GLES_CM=FALSE -DSWIFTSHADER_BUILD_VULKAN=TRUE -DSWIFTSHADER_BUILD_PVR=FALSE -DSWIFTSHADER_BUILD_TESTS=FALSE -DSWIFTSHADER_ENABLE_ASTC=FALSE -DSWIFTSHADER_WARNINGS_AS_ERRORS=FALSE -DREACTOR_BACKEND=Subzero -DREACTOR_DEFAULT_OPT_LEVEL=Default -DCMAKE_BUILD_TYPE=Release -DNCNN_BUILD_TESTS=ON ..
        cmake --build . --config Release -j 2
        mkdir "$env:GITHUB_WORKSPACE/swiftshader-install"
        Copy-Item -Path "Windows\*" -Destination "$env:GITHUB_WORKSPACE\swiftshader-install"
        Move-Item -Path "$env:GITHUB_WORKSPACE\swiftshader-install\vk_swiftshader_icd.json" -Destination "$env:GITHUB_WORKSPACE\swiftshader-install\igvk64.json"
    - name: configure
      run: |
        $env:VULKAN_SDK="$(pwd)/VulkanSDK"
        mkdir build; cd build
        cmake -DProtobuf_INCLUDE_DIR="$env:GITHUB_WORKSPACE\protobuf-install\include" -DProtobuf_LIBRARIES="$env:GITHUB_WORKSPACE\protobuf-install\lib\libprotobuf.lib" -DProtobuf_PROTOC_EXECUTABLE="$env:GITHUB_WORKSPACE\protobuf-install\bin\protoc.exe" -DNCNN_VULKAN=ON -DNCNN_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build --config Release -j 2
    - name: test
      run: |
        Copy-Item -Path '.\VulkanSDK\vulkan-1.dll' -Destination 'build\tests'
        $env:VK_ICD_FILENAMES="$env:GITHUB_WORKSPACE\swiftshader-install\igvk64.json"
        cd build; ctest -C Release --output-on-failure -j 2
